/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { EditorRoleService } from "../editorRole.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { EditorRoleCreateInput } from "./EditorRoleCreateInput";
import { EditorRole } from "./EditorRole";
import { EditorRoleFindManyArgs } from "./EditorRoleFindManyArgs";
import { EditorRoleWhereUniqueInput } from "./EditorRoleWhereUniqueInput";
import { EditorRoleUpdateInput } from "./EditorRoleUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class EditorRoleControllerBase {
  constructor(
    protected readonly service: EditorRoleService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: EditorRole })
  @nestAccessControl.UseRoles({
    resource: "EditorRole",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createEditorRole(
    @common.Body() data: EditorRoleCreateInput
  ): Promise<EditorRole> {
    return await this.service.createEditorRole({
      data: data,
      select: {
        canApproveData: true,
        canDeleteData: true,
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [EditorRole] })
  @ApiNestedQuery(EditorRoleFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "EditorRole",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async editorRoles(@common.Req() request: Request): Promise<EditorRole[]> {
    const args = plainToClass(EditorRoleFindManyArgs, request.query);
    return this.service.editorRoles({
      ...args,
      select: {
        canApproveData: true,
        canDeleteData: true,
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: EditorRole })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EditorRole",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async editorRole(
    @common.Param() params: EditorRoleWhereUniqueInput
  ): Promise<EditorRole | null> {
    const result = await this.service.editorRole({
      where: params,
      select: {
        canApproveData: true,
        canDeleteData: true,
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: EditorRole })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EditorRole",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateEditorRole(
    @common.Param() params: EditorRoleWhereUniqueInput,
    @common.Body() data: EditorRoleUpdateInput
  ): Promise<EditorRole | null> {
    try {
      return await this.service.updateEditorRole({
        where: params,
        data: data,
        select: {
          canApproveData: true,
          canDeleteData: true,
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: EditorRole })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EditorRole",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteEditorRole(
    @common.Param() params: EditorRoleWhereUniqueInput
  ): Promise<EditorRole | null> {
    try {
      return await this.service.deleteEditorRole({
        where: params,
        select: {
          canApproveData: true,
          canDeleteData: true,
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
