/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, AdminRole as PrismaAdminRole } from "@prisma/client";

export class AdminRoleServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.AdminRoleCountArgs, "select">
  ): Promise<number> {
    return this.prisma.adminRole.count(args);
  }

  async adminRoles<T extends Prisma.AdminRoleFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.AdminRoleFindManyArgs>
  ): Promise<PrismaAdminRole[]> {
    return this.prisma.adminRole.findMany<Prisma.AdminRoleFindManyArgs>(args);
  }
  async adminRole<T extends Prisma.AdminRoleFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.AdminRoleFindUniqueArgs>
  ): Promise<PrismaAdminRole | null> {
    return this.prisma.adminRole.findUnique(args);
  }
  async createAdminRole<T extends Prisma.AdminRoleCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.AdminRoleCreateArgs>
  ): Promise<PrismaAdminRole> {
    return this.prisma.adminRole.create<T>(args);
  }
  async updateAdminRole<T extends Prisma.AdminRoleUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.AdminRoleUpdateArgs>
  ): Promise<PrismaAdminRole> {
    return this.prisma.adminRole.update<T>(args);
  }
  async deleteAdminRole<T extends Prisma.AdminRoleDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.AdminRoleDeleteArgs>
  ): Promise<PrismaAdminRole> {
    return this.prisma.adminRole.delete(args);
  }
}
